blank_issues_enabled: true
contact_links:
  - name: Monacoin Core Security Policy
    url: https://github.com/bitcoin/bitcoin/blob/master/SECURITY.md
    about: View security policy
  - name: Monacoin Core Developers
    url: https://bitcoincore.org
    about: Monacoin Core homepage
